#!/bin/zsh

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

#### INITIALIZE STARSHIP
eval "$(starship init zsh)"

#### ADD TAB COMPLETIONS
source <(flux completion zsh)
source <(chezmoi completion zsh)
source <(gh completion -s zsh)
source <(kubectl completion zsh)
source <(starship completions zsh)