apps:

  # Personal Apps
  cura:
    forPersonal: true
    windows:
      id: "Ultimaker.Cura"
      method: "winget"

  steam:
    forPersonal: true
    windows:
      id: "Valve.Steam"
      method: "winget"

  blender:
    forPersonal: true
    windows:
      id: "BlenderFoundation.Blender"
      method: "winget"

  calibre:
    forPersonal: true
    windows: 
      id: "calibre.calibre"
      method: "winget"

  # CLI Tools
  mise:
    forPersonal: false
    windows:
      id: "jdx.mise"
      method: "winget"

  clink:
    forPersonal: false
    windows:
      id: "chrisant996.Clink"
      method: "winget"

  git:
    forPersonal: false
    windows:
      id: "Git.Git"
      method: "winget"

  # Browser
  firefox-dev:
    forPersonal: false
    windows:
      id: "Mozilla.Firefox.DeveloperEdition"
      method: "winget"
    darwin:
      id: "firefox@developer-edition"
      method: "brew-cask"

  chrome:
    forPersonal: false
    windows:
      id: "Google.Chrome"
      method: "winget"
    darwin:
      id: "google-chrome"
      method: "brew-cask"

  # Media
  icloud:
    forPersonal: true
    windows:
      id: "icloud"
      method: "choco"

  vlc:
    forPersonal: true
    windows:
      id: "VideoLAN.VLC"
      method: "winget"
    darwin:
      id: "vlc"
      method: "brew-cask"

  open-office:
    forPersonal: false
    windows:
      id: "Apache.OpenOffice"
      method: "winget"

  # Developer Tools
  vscode:
    forPersonal: false
    windows:
      id: "Microsoft.VisualStudioCode"
      method: "winget"
    darwin:
      id: "visual-studio-code"
      method: "brew"

  postman:
    forPersonal: false
    windows:
      id: "Postman.Postman"
      method: "winget"
    darwin:
      id: "postman"
      method: "brew-cask"

  yubikey-manager:
    forPersonal: false
    windows:
      id: "Yubico-YubikeyManager"
      method: "winget"

  putty:
    forPersonal: false
    windows:
      id: "PuTTY.PuTTY"
      method: "winget"

  iterm2:
    forPersonal: false
    darwin:
      id: "iterm2"
      method: "brew-cask"

  # Second Brain

  obsidian:
    forPersonal: false
    windows:
      id: "Obsidian.Obsidian"
      method: "winget"
    darwin:
      id: "obsidian"
      method: "brew-cast"

  # Extra
  cask-versions:
    forPersonal: false
    darwin:
      id: "homebrew/cask-versions"
      method: "brew-tap"

  cask-fonts:
    forPersonal: false
    darwin:
      id: "homebrew/cask-fonts"
      method: "brew-tap"

  zsh-autosuggestions:
    forPersonal: false
    darwin:
      id: "zsh-autosuggestions"
      method: "brew"

  7zip:
    forPersonal: false
    windows:
      id: "7zip"
      method: "choco"
    darwin:
      id: "p7zip"
      method: "brew"
  
  # Fonts
  fira-code-mono:
    forPersonal: false
    windows:
      id: "nerd-fonts-firamono"
      method: "choco"
    darwin:
      id: "font-fira-mono"
      method: "brew-cask"
  
  cascadia-code:
    forPersonal: false
    windows:
      id: "cascadiacode"
      method: "choco"
    darwin:
      id: "font-cascadia-code"
      method: "brew-cask"
  
  cascadia-code-pl:
    forPersonal: false
    windows:
      id: "cascadiacodepl"
      method: "choco"
    darwin:
      id: "font-cascadia-code-pl"
      method: "brew-cask"
  
  cascadia-mono:
    forPersonal: false
    windows:
      id: "firacode"
      method: "choco"
    darwin:
      id: "font-cascadia-mono"
      method: "brew-cask"
  
  cascadia-mono-pl:
    forPersonal: false
    windows:
      id: "firacode"
      method: "choco"
    darwin:
      id: "font-cascadia-mono-pl"
      method: "brew-cask"