apps:

  # Personal Apps
  cura:
    forPersonal: true
    windows:
      id: "Ultimaker.Cura"
      method: "winget"

  steam:
    forPersonal: true
    windows:
      id: "Valve.Steam"
      method: "winget"

  blender:
    forPersonal: true
    windows:
      id: "BlenderFoundation.Blender"
      method: "winget"

  calibre:
    forPersonal: true
    windows: 
      id: "calibre.calibre"
      method: "winget"

  # Shells
  fish:
    forPersonal: false
    darwin:
      id: "fish"
      method: "brew"

  # CLI Tools
  mise:
    forPersonal: false
    windows:
      id: "jdx.mise"
      method: "winget"
    darwin:
      id: "mise"
      method: "brew"

  clink:
    forPersonal: false
    windows:
      id: "chrisant996.Clink"
      method: "winget"

  git:
    forPersonal: false
    windows:
      id: "Git.Git"
      method: "winget"

  powershell:
    forPersonal: false
    windows:
      id: "Microsoft.PowerShell"
      method: "winget"

  # Browser
  firefox-dev:
    forPersonal: false
    windows:
      id: "Mozilla.Firefox.DeveloperEdition"
      method: "winget"
    darwin:
      id: "firefox@developer-edition"
      method: "brew-cask"

  chrome:
    forPersonal: false
    windows:
      id: "Google.Chrome"
      method: "winget"
    darwin:
      id: "google-chrome"
      method: "brew-cask"

  # Media
  icloud:
    forPersonal: true
    windows:
      id: "9PKTQ5699M62"
      method: "winget"

  vlc:
    forPersonal: true
    windows:
      id: "VideoLAN.VLC"
      method: "winget"
    darwin:
      id: "vlc"
      method: "brew-cask"

  open-office:
    forPersonal: false
    windows:
      id: "Apache.OpenOffice"
      method: "winget"

  # Developer Tools
  vscode:
    forPersonal: false
    windows:
      id: "Microsoft.VisualStudioCode"
      method: "winget"
    darwin:
      id: "visual-studio-code"
      method: "brew-cask"

  postman:
    forPersonal: false
    windows:
      id: "Postman.Postman"
      method: "winget"
    darwin:
      id: "postman"
      method: "brew-cask"

  yubikey-manager:
    forPersonal: false
    windows:
      id: "Yubico.YubikeyManager"
      method: "winget"

  putty:
    forPersonal: false
    windows:
      id: "PuTTY.PuTTY"
      method: "winget"

  iterm2:
    forPersonal: false
    darwin:
      id: "iterm2"
      method: "brew-cask"

  # Second Brain
  obsidian:
    forPersonal: false
    windows:
      id: "Obsidian.Obsidian"
      method: "winget"
    darwin:
      id: "obsidian"
      method: "brew-cast"

  zsh-autosuggestions:
    forPersonal: false
    darwin:
      id: "zsh-autosuggestions"
      method: "brew"

  7zip:
    forPersonal: false
    windows:
      id: "7zip"
      method: "choco"
    darwin:
      id: "p7zip"
      method: "brew"
  
  # Fonts
  fira-code-mono:
    forPersonal: false
    windows:
      id: "nerd-fonts-firamono"
      method: "choco"
    darwin:
      id: "font-fira-mono"
      method: "brew-cask"
  
  nerd-fonts-firacode:
    forPersonal: false
    windows:
      id: "nerd-fonts-firacode"
      method: "choco"
    darwin:
      id: "font-fira-code-nerd-font"
      method: "brew-cask"