#!/bin/zsh

#### INITIALIZE STARSHIP
eval "$(starship init zsh)"

#### ADD TAB COMPLETIONS
source <(flux completion zsh)
source <(chezmoi completion zsh)
source <(gh completion -s zsh)
source <(kubectl completion zsh)
source <(starship completions zsh)