[tools]
node = "22"
"python" = "latest"
"uv" = "latest"
"github:cli/cli" = { version = "latest", exe = "gh" }
"aqua:kubernetes/kubernetes/kubectl" = "latest"
"github:jqlang/jq" = "latest"
"github:DopplerHQ/cli" = "latest"
"aqua:JanDeDobbeleer/oh-my-posh" = "latest"
"aqua:cheat/cheat" = "latest"
"aqua:hashicorp/terraform" = "latest"
"aqua:terraform-docs/terraform-docs" = "latest"
"github:junegunn/fzf" = "latest" # Required for navi
"github:denisidoro/navi" = "2.22.1"
"aqua:sxyazi/yazi" = "latest"
"aqua:neovim/neovim" = "latest"
"github:twpayne/chezmoi" = "latest"
"aqua:yarnpkg/berry" = "latest"
"aqua:nektos/act" = "latest"
"github:ebullient/ttrpg-convert-cli" = "latest"
"aqua:astral-sh/uv" = "latest"
"pipx:graphifyy" = "latest"

[env]
_.file = ".env"
_.path = ['{{cwd}}/node_modules/.bin']
MISE_PWSH_CHPWD_WARNING = 0
NAVI_CONFIG = "~/.config/navi/config.yml"
